Repository WyriHaximus/github-action-next-semvers, pull requests merged in 2020-06, with the labels that each got.

#8 Replace "Github" with "GitHub"
  README.md
Labels: documentation

#9 Add optimized Docker based set up
  .docker/security/docker-compose.yml
  .editorconfig
  .github/CODEOWNERS
  .github/boring-cyborg.yml
  .github/dependabot.yml
  .github/settings.yml
  .github/workflows/ci.yml
  .github/workflows/craft-release.yaml
  .github/workflows/set-milestone-on-pr.yaml
  Dockerfile
  Dockerfile-build
  README.md
Labels: enhancement

#11 Fix Boring Cyborg Config
  .github/boring-cyborg.yml
Labels: Bug 🐞
